# Default values for helm-repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# this value will default to not-restarted
# if you change the value in your env specific values.yaml to anything else
# and do a git push, pods will restart.
# ideally you put the date and time of the git push / restart
restart: not-restarted

application:
  containerPort: 8080
  #healthCheck: <path-to-healthcheck> (e.g. hotel-content/sys-info/health )
  namespace: development
  # number of replicas to start with before HPA gets involved
  replicaCount: 1
  serviceport: 8080

env:
  SPRING_PROFILES_ACTIVE: "release"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

image:
  pullPolicy: Always
  repository: gcr.io/automatic-asset-253215/a-app-image
  #tag: build-id-${BUILD_NUMBER}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rollingUpdate:
  maxSurge: 1

service:
  type: LoadBalancer
  # nodePort: 80
  port: 80
  # targetport: 8084
#  portName: grpc

#readinessProbe:
#  path: "/bin/grpc_health_probe"
#  port: 7070
#livenessProbe:
#  path: "/bin/grpc_health_probe"
#  port: 7070

resources:
  requests:
    cpu: 250m
    memory: 900Mi
  limits:
    cpu: 500m
    memory: 1Gi









# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths: []

nodeSelector: {}

tolerations: []

affinity: {}
