# Default values for helm-repo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# this value will default to not-restarted
# if you change the value in your env specific values.yaml to anything else
# and do a git push, pods will restart.
# ideally you put the date and time of the git push / restart
restart: not-restarted

application:
  containerPort: 8084
  #healthCheck: <path-to-healthcheck> (e.g. hotel-content/sys-info/health )
  namespace: development
  # number of replicas to start with before HPA gets involved
  replicaCount: 1
  serviceport: 8084

env:
  SPRING_PROFILES_ACTIVE: "release"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

image:
  pullPolicy: Always
  repository: gcr.io/techocamp-221315/assessment-server-dev
  #tag: build-id-${BUILD_NUMBER}

rollingUpdate:
  maxSurge: 1

service:
  type: ClusterIP
#  nodePort: 8080
  port: 80
  targetport: 8084
#  portName: grpc

#readinessProbe:
#  path: "/bin/grpc_health_probe"
#  port: 7070
#livenessProbe:
#  path: "/bin/grpc_health_probe"
#  port: 7070

resources:
  requests:
    cpu: 250m
    memory: 900Mi
  limits:
    cpu: 500m
    memory: 1Gi